package com.psildave.punchtheclock.data.database

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Entity representing a time clock punch record in the database.
 *
 * @property id Unique identifier automatically generated by the database.
 * @property punchType Type of the punch (e.g., CLOCK_IN, CLOCK_OUT).
 * @property timeString Formatted textual representation of the time.
 * @property locationAddress Address or coordinates of where the clock was punched.
 * @property timestamp Milliseconds timestamp of the moment of the punch.
 */
@Entity(tableName = "punch_records")
data class PunchEntity(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val punchType: String,
    val timeString: String,
    val locationAddress: String,
    val timestamp: Long = System.currentTimeMillis()
)
